language: java
jdk:
  - oraclejdk8
before_install:
  - git submodule update --init --recursive
install: mvn install -DskipTests=true
services: mongodb 
script: mvn verify
notifications:
  email:
    - maurizio@softinstigate.com