## RESTHeart security configuration file for Db Identity Manager.

# cache-ttl is in millisecond
# cache-expire-policy valid values: NEVER, AFTER_WRITE, AFTER_READ

---
dbim:
    - db: userbase
      coll: accounts
      cache-enabled: false
      cache-size: 1000
      cache-ttl: 60000
      cache-expire-policy: AFTER_WRITE